export const compareProducts = [
  {
    id: 1,
    name: "MacBook Air (2020) 13.3-inch - Apple M1 8-core and 7-core GPU - 8GB RAM - SSD 256GB",
    price: "$6666.99",
    image: "/images/category.png",
    inStock: true,
    rating: 4,
    totalReviews: 1000,
    stores: 4,
    options: "6 colours, 3 storage sizes",
  },
  {
    id: 2,
    name: "MacBook Air (2020) 13.3-inch - Apple M1 8-core and 7-core GPU - 8GB RAM - SSD 256GB",
    price: "$6666.99",
    image: "/images/category.png",
    inStock: true,
    rating: 4,
    totalReviews: 1000,
    stores: 4,
    options: "6 colours, 3 storage sizes",
  },
  {
    id: 3,
    name: "MacBook Air (2020) 13.3-inch - Apple M1 8-core and 7-core GPU - 8GB RAM - SSD 256GB",
    price: "$6666.99",
    image: "/images/category.png",
    inStock: true,
    rating: 4,
    totalReviews: 1000,
    stores: 4,
    options: "6 colours, 3 storage sizes",
  },
];